// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQoUHYnyJcNmKlSfvypLzz_arl1OwcqM',
    appId: '1:68111004900:web:19d4d2e3571a48021968f1',
    messagingSenderId: '68111004900',
    projectId: 'ecommerce-47f22',
    authDomain: 'ecommerce-47f22.firebaseapp.com',
    storageBucket: 'ecommerce-47f22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ogrmqJ5WX4Etu7w1OTbMZrWHCwAFXic',
    appId: '1:68111004900:android:a4054fef09901d021968f1',
    messagingSenderId: '68111004900',
    projectId: 'ecommerce-47f22',
    storageBucket: 'ecommerce-47f22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4opqhDtlP2sRHlzY3Q_xd_-tJ33c4sN4',
    appId: '1:68111004900:ios:5eb9278eff5334d91968f1',
    messagingSenderId: '68111004900',
    projectId: 'ecommerce-47f22',
    storageBucket: 'ecommerce-47f22.appspot.com',
    androidClientId: '68111004900-p2ehin60qaif7sjsjbaim9oin36oaurh.apps.googleusercontent.com',
    iosClientId: '68111004900-8k4duqt5cspflg98v7ip0vvq8cbfvlgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStore',
  );

}